/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import Modelo.Cliente;
import Modelo.Habitacion;
import Modelo.Reserva;
import Vista.PaginaPrincipal;
import Vista.PaginaPrincipal;
import Vista.PaginaPrincipal;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author usuario
 */
public class PnlFactura_1 extends javax.swing.JPanel {

    DefaultTableModel dtmModelo;
    Habitacion c;
    Cliente c1;
    int indiceHabitacionSeleccionada = -1;
    Reserva r;
    private int diasTranscurridos;

    /**
     * Creates new form factra
     */
    public PnlFactura_1() {
        initComponents();
        /*PnlFondo3.setVisible(true);*/
        dtmModelo = new DefaultTableModel();
        dtmModelo.addColumn("Tipo de habitacion");
        dtmModelo.addColumn("Piso");
        dtmModelo.addColumn("Numero de habitacion");
        dtmModelo.addColumn("Capacidad");
        dtmModelo.addColumn("Precio");
        lblNoVisibles();
        tblHabitacion21.setModel(dtmModelo);
        for (Cliente r : PaginaPrincipal.listaDeClientes) {
            lblCliente4.setText(r.getNombre() + " " + r.getApellido());
            /*cmbClientes.addItem(r.getNombre() + " " + r.getApellido());*/
        }
        for (Habitacion c : PaginaPrincipal.listaDeHabitaciones) {
            dtmModelo.addRow(new Object[]{c.getTipoDeHabitacion(), c.getPiso(),
                c.getNumeroDeHabitacion(),
                c.getCapacidad(), c.getPrecio()});
        }
        indiceHabitacionSeleccionada = -1;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btgFormaDePago = new javax.swing.ButtonGroup();
        fondo = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        rbtTransferencia = new javax.swing.JRadioButton();
        rbtTarjeta = new javax.swing.JRadioButton();
        jdcFechaIngreso = new com.toedter.calendar.JDateChooser();
        jdcFechaSalida = new com.toedter.calendar.JDateChooser();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblHabitacion21 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDescripccion = new javax.swing.JTextArea();
        PnlFondo3 = new javax.swing.JPanel();
        lblNombreFactura3 = new javax.swing.JLabel();
        lblNombreCliente = new javax.swing.JLabel();
        lblFechaIngreso3 = new javax.swing.JLabel();
        lblFechaIngreso = new javax.swing.JLabel();
        lblFechaSalida3 = new javax.swing.JLabel();
        lblFechaSalida = new javax.swing.JLabel();
        lblTipoHabitacion3 = new javax.swing.JLabel();
        lblTipoHabitacionFactura3 = new javax.swing.JLabel();
        lblIVA3 = new javax.swing.JLabel();
        lblTotal3 = new javax.swing.JLabel();
        lblIVA = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        lblFormaPago3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblFormaPagoFactura3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblSubTotal = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnFactura = new javax.swing.JButton();
        btnNuevaReserva = new javax.swing.JButton();
        btnCalcuclarReserva = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lblCliente4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 102, 204));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        fondo.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jPanel1.setBackground(new java.awt.Color(0, 102, 204));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Fecha ingreso");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Fecha de salida");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Cliente");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Forma de pago");
        jLabel4.setToolTipText("");

        btgFormaDePago.add(rbtTransferencia);
        rbtTransferencia.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rbtTransferencia.setForeground(new java.awt.Color(255, 255, 255));
        rbtTransferencia.setText("Transferencia");

        btgFormaDePago.add(rbtTarjeta);
        rbtTarjeta.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rbtTarjeta.setForeground(new java.awt.Color(255, 255, 255));
        rbtTarjeta.setText("Tarjeta de credito");

        jdcFechaIngreso.setDateFormatString("dd/MM/yyyy");

        jdcFechaSalida.setDateFormatString("dd/MM/yyyy");

        jScrollPane5.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane5.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        tblHabitacion21.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblHabitacion21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblHabitacion21MouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tblHabitacion21);

        txtDescripccion.setColumns(20);
        txtDescripccion.setRows(5);
        txtDescripccion.setBorder(javax.swing.BorderFactory.createTitledBorder("Descripción de habitación"));
        jScrollPane2.setViewportView(txtDescripccion);

        PnlFondo3.setBackground(new java.awt.Color(255, 255, 255));
        PnlFondo3.setBorder(javax.swing.BorderFactory.createTitledBorder("Factura"));
        PnlFondo3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblNombreFactura3.setText("Nombre");

        lblNombreCliente.setText("nombre");

        lblFechaIngreso3.setText("Fecha de Ingreso");

        lblFechaIngreso.setText("fecha");

        lblFechaSalida3.setText("Fecha de Salida");

        lblFechaSalida.setText("salida");

        lblTipoHabitacion3.setText("Tipo de Habitación");

        lblTipoHabitacionFactura3.setText("jLabel1");

        lblIVA3.setText("%IVA");

        lblTotal3.setText("Total");

        lblIVA.setText("iva");

        lblTotal.setText("total");

        lblFormaPago3.setText("Forma de Pago");

        lblFormaPagoFactura3.setText("jLabel1");

        jLabel6.setText("SubTotal");

        lblSubTotal.setText("subtotal");

        javax.swing.GroupLayout PnlFondo3Layout = new javax.swing.GroupLayout(PnlFondo3);
        PnlFondo3.setLayout(PnlFondo3Layout);
        PnlFondo3Layout.setHorizontalGroup(
            PnlFondo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlFondo3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(PnlFondo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PnlFondo3Layout.createSequentialGroup()
                        .addGroup(PnlFondo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblIVA3, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PnlFondo3Layout.createSequentialGroup()
                                .addGap(193, 193, 193)
                                .addComponent(jLabel5))
                            .addGroup(PnlFondo3Layout.createSequentialGroup()
                                .addGap(158, 158, 158)
                                .addComponent(lblFormaPagoFactura3, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PnlFondo3Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addGroup(PnlFondo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PnlFondo3Layout.createSequentialGroup()
                                        .addComponent(lblTipoHabitacion3, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblTipoHabitacionFactura3, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lblFormaPago3, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(PnlFondo3Layout.createSequentialGroup()
                        .addGroup(PnlFondo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PnlFondo3Layout.createSequentialGroup()
                                .addGroup(PnlFondo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblTotal3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(39, 39, 39)
                                .addGroup(PnlFondo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblIVA, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(PnlFondo3Layout.createSequentialGroup()
                                .addComponent(lblNombreFactura3, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PnlFondo3Layout.createSequentialGroup()
                                .addGroup(PnlFondo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblFechaIngreso3, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblFechaSalida3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(PnlFondo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblFechaIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblFechaSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        PnlFondo3Layout.setVerticalGroup(
            PnlFondo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlFondo3Layout.createSequentialGroup()
                .addGroup(PnlFondo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PnlFondo3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblNombreFactura3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PnlFondo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFechaIngreso3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFechaIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PnlFondo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFechaSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFechaSalida3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PnlFondo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PnlFondo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIVA3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIVA, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(PnlFondo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotal3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(90, 90, 90)
                .addGroup(PnlFondo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PnlFondo3Layout.createSequentialGroup()
                        .addGroup(PnlFondo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTipoHabitacion3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTipoHabitacionFactura3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PnlFondo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFormaPago3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblFormaPagoFactura3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(PnlFondo3Layout.createSequentialGroup()
                        .addGap(232, 232, 232)
                        .addComponent(jLabel5))))
        );

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Elija el tipo de habitación de su preferencia");

        btnFactura.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnFactura.setText("Facturar y Guardar");
        btnFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFacturaActionPerformed(evt);
            }
        });

        btnNuevaReserva.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnNuevaReserva.setText("Nueva Reserva");
        btnNuevaReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevaReservaActionPerformed(evt);
            }
        });

        btnCalcuclarReserva.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCalcuclarReserva.setText("Calcular Precio");
        btnCalcuclarReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcuclarReservaActionPerformed(evt);
            }
        });

        btnGuardar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnSalir.setBackground(new java.awt.Color(0, 0, 153));
        btnSalir.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setText("SALIR");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        lblCliente4.setBackground(new java.awt.Color(0, 0, 0));
        lblCliente4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblCliente4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblCliente4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(btnGuardar)
                .addGap(90, 90, 90)
                .addComponent(btnCalcuclarReserva)
                .addGap(71, 71, 71)
                .addComponent(btnFactura)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSalir)
                .addGap(97, 97, 97))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(7, 7, 7)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jdcFechaSalida, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(12, 12, 12)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(rbtTransferencia)
                                                    .addComponent(rbtTarjeta)))
                                            .addComponent(jdcFechaIngreso, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane5))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(btnNuevaReserva))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(PnlFondo3, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(85, 85, 85))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(0, 39, Short.MAX_VALUE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jdcFechaIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(63, 63, 63)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jdcFechaSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(45, 45, 45)
                                        .addComponent(rbtTransferencia)
                                        .addGap(27, 27, 27)
                                        .addComponent(rbtTarjeta)))
                                .addGap(22, 22, 22)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnGuardar)
                            .addComponent(btnFactura)
                            .addComponent(btnCalcuclarReserva)
                            .addComponent(btnSalir))
                        .addGap(106, 106, 106))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(PnlFondo3, javax.swing.GroupLayout.PREFERRED_SIZE, 356, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(btnNuevaReserva)
                        .addGap(217, 217, 217))))
        );

        fondo.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, 1035, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tblHabitacion21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblHabitacion21MouseClicked
        // TODO add your handling code here:
        indiceHabitacionSeleccionada = tblHabitacion21.getSelectedRow();
        Habitacion HabitacionSeleccionada = PaginaPrincipal.listaDeHabitaciones.
                get(indiceHabitacionSeleccionada);
        borrarAreaDeTexto();
        if (HabitacionSeleccionada.getTipoDeHabitacion().equals("Matrimonial")) {
            txtDescripccion.append(HabitacionSeleccionada.habitacionDoble() + "\n");
        }
        if (HabitacionSeleccionada.getTipoDeHabitacion().equals("Triple")) {
            txtDescripccion.append(HabitacionSeleccionada.habitacionTriple() + "\n");
        }
        if (HabitacionSeleccionada.getTipoDeHabitacion().equals("Simple")) {
            txtDescripccion.append(HabitacionSeleccionada.habitacionSimple() + "\n");
        }

        if (HabitacionSeleccionada.getTipoDeHabitacion().equals("Cuadruple")) {
            txtDescripccion.append(HabitacionSeleccionada.habitacionCuadruple() + "\n");
        }
        if (HabitacionSeleccionada.getTipoDeHabitacion().equals("ConnectingRooms")) {
            txtDescripccion.append(HabitacionSeleccionada.habitacionConnectingRooms() + "\n");
        }
        if (HabitacionSeleccionada.getTipoDeHabitacion().equals("Suite")) {
            txtDescripccion.append(HabitacionSeleccionada.Suite() + "\n");
        }

    }//GEN-LAST:event_tblHabitacion21MouseClicked

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(fondo,
                    "Datos previos guardados con éxito");
        JOptionPane.showMessageDialog(fondo,
                    "Puede calcular el precio según su instancia");
        guarfarInformacion();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFacturaActionPerformed
       /* String nombreArchivo = "Facturas";
        String carpeta = System.getProperty("user.dir");
        String direccionCompleta = carpeta + "/" + "Facturas" + ".txt";
        FileWriter ubicacion = null;*/
       JOptionPane.showMessageDialog(fondo,
                    "Los Datos registrados se guardarán en factura");
       PnlFondo3.setVisible(true);
            factura();
        /*try {
            JOptionPane.showMessageDialog(fondo,
                    "Datos Guardados de la Factura");
        
            ubicacion = new FileWriter(direccionCompleta);
            
        } catch (IOException ex) {
            
            /*PnlFactura fac = new PnlFactura ();
        fac.setVisible(true);*/
        
    }//GEN-LAST:event_btnFacturaActionPerformed

    private void btnNuevaReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevaReservaActionPerformed
        lblNoVisibles();
        seleccionarHabitacion();
        limpiar();
    }//GEN-LAST:event_btnNuevaReservaActionPerformed

    private void btnCalcuclarReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcuclarReservaActionPerformed

        String tipoHabitacion = ""; // Obtener el tipo de habitación seleccionado
        Habitacion habitacionSeleccionada = PaginaPrincipal.listaDeHabitaciones.
                get(indiceHabitacionSeleccionada);
        tipoHabitacion = habitacionSeleccionada.getTipoDeHabitacion();
        int diasTranscurridos = this.diasTranscurridos; // Obtener los días transcurridos
        JOptionPane.showMessageDialog(fondo,
                    "Precio calculado con éxito");

        double precioPorNoche = 0.0;
        switch (tipoHabitacion) {
            case "Matrimonial":
                precioPorNoche = 80.0;
                break;
            case "Triple":
                precioPorNoche = 115.0;
                break;
            case "Simple":
                precioPorNoche = 50.0;
                break;
            case "Cuadruple":
                precioPorNoche = 125.0;
                break;
            case "ConnectingRooms":
                precioPorNoche = 150.0;
                break;
            case "Suite":
                precioPorNoche = 180.0;
                break;
            default:
                break;
        }

        double precioTotal = precioPorNoche * diasTranscurridos;
        txtDescripccion.append("\nPrecio total de la reserva: " + precioTotal
                + "$");
    }//GEN-LAST:event_btnCalcuclarReservaActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(fondo,
                    "Desea salir del programa?");

        System.exit(WIDTH);
    }//GEN-LAST:event_btnSalirActionPerformed
    private void limpiar() {
        lblCliente4.setText("");
        jdcFechaIngreso.setCalendar(null);
        jdcFechaSalida.setCalendar(null);
        btgFormaDePago.clearSelection();
        txtDescripccion.setText("");
    }

    private void borrarAreaDeTexto() {
        txtDescripccion.setText("");
    }

    private void seleccionarHabitacion() {
        if (indiceHabitacionSeleccionada != -1) {
            PaginaPrincipal.listaDeHabitaciones.remove(indiceHabitacionSeleccionada);
            limpiarTablaDeClientes();
            agregarListaCompletaALaTabla();
            indiceHabitacionSeleccionada = -1;
        }

    }

    private void limpiarTablaDeClientes() {
        for (int i = 0; i < tblHabitacion21.getRowCount(); i++) {
            dtmModelo.removeRow(i);
            i--;//decremento asi o asi; i-=1
        }
    }

    private void agregarListaCompletaALaTabla() {
        for (Habitacion c : PaginaPrincipal.listaDeHabitaciones) {
            agregarHabitacionesALaTabla(c);
        }
    }

    private void agregarHabitacionesALaTabla(Habitacion h) {
        dtmModelo.addRow(new Object[]{h.getTipoDeHabitacion(), h.getPiso(),
            h.getNumeroDeHabitacion(),
            h.getCapacidad(), h.getPrecio()});
    }

    private void agregarPanel(JPanel pnl) {
        pnl.setSize(1000, 620);
        pnl.setLocation(0, 0);
        fondo.removeAll();
        fondo.add(pnl);
        fondo.revalidate();
        fondo.repaint();

    }

    private void guarfarInformacion() {
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss",
                new Locale("es"));
        String fechaIngreso = sdf.format(jdcFechaIngreso.getDate());
        String fechaSalida = sdf.format(jdcFechaSalida.getDate());
        Date fecha1 = jdcFechaIngreso.getDate();
        Date fecha2 = jdcFechaSalida.getDate();
        long diffMillis = fecha2.getTime() - fecha1.getTime();
        diasTranscurridos = (int) (diffMillis / 86400000);
        r = new Reserva(fechaIngreso, fechaSalida);
        if (rbtTransferencia.isSelected()) {
            r.setFormaDePago("Transferencia");
        }
        if (rbtTarjeta.isSelected()) {
            r.setFormaDePago("Tarjeta de credito");
        }
        txtDescripccion.append("Fecha ingreso: " + r.getFechaIngreso() + "\nFecha salida: "
                + r.getFechaSalida() + "\nForma de pago: " + r.getFormaDePago()
                + "\n" + "Dias reservados: " + diasTranscurridos);
    }

    public void factura() {
        for (Cliente r : PaginaPrincipal.listaDeClientes) {
            lblNombreCliente.setText(r.getNombre() + " " + r.getApellido());
        }

        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss",
                new Locale("es"));
        String fechaIngreso = sdf.format(jdcFechaIngreso.getDate());
        String fechaSalida = sdf.format(jdcFechaSalida.getDate());
        Date fecha1 = jdcFechaIngreso.getDate();
        Date fecha2 = jdcFechaSalida.getDate();
        lblFechaIngreso.setText(fechaIngreso);

        lblFechaSalida.setText(fechaSalida);
        indiceHabitacionSeleccionada = tblHabitacion21.getSelectedRow();
        Habitacion HabitacionSeleccionada = PaginaPrincipal.listaDeHabitaciones.
                get(indiceHabitacionSeleccionada);
        // borrarAreaDeTexto();
        if (HabitacionSeleccionada.getTipoDeHabitacion().equals("Matrimonial")) {
            lblTipoHabitacionFactura3.setText("Matrrmonial");
            lblTipoHabitacionFactura3.setVisible(true);
        }
        if (HabitacionSeleccionada.getTipoDeHabitacion().equals("Triple")) {
            lblTipoHabitacionFactura3.setText("Triple");
            lblTipoHabitacionFactura3.setVisible(true);
        }
        if (HabitacionSeleccionada.getTipoDeHabitacion().equals("Simple")) {
            lblTipoHabitacionFactura3.setText("Simple");
            lblTipoHabitacionFactura3.setVisible(true);
        }

        if (HabitacionSeleccionada.getTipoDeHabitacion().equals("Cuadruple")) {
            lblTipoHabitacionFactura3.setText("Cuadruple");
            lblTipoHabitacionFactura3.setVisible(true);
        }
        if (HabitacionSeleccionada.getTipoDeHabitacion().equals("Connecting Rooms")) {
            lblTipoHabitacionFactura3.setText("Connecting Rooms");
            lblTipoHabitacionFactura3.setVisible(true);
        }
        if (HabitacionSeleccionada.getTipoDeHabitacion().equals("Suite")) {
            lblTipoHabitacionFactura3.setText("Suite");
            lblTipoHabitacionFactura3.setVisible(true);

        }
        if (rbtTransferencia.isSelected()) {
            r.setFormaDePago("Transferencia");
        }
        lblFormaPagoFactura3.setVisible(true);
        if (rbtTarjeta.isSelected()) {
            r.setFormaDePago("Tarjeta de credito");
        }

        lblIVA.setText("0,12");
        lblTotal.setText("" + calcularPrecioTotal());

        lblSubTotal.setText("" + calcuclarSubTotal());
        lblVisibles();
    }
     private void lblVisibles() {
        lblFechaIngreso.setVisible(true);
        lblFechaSalida.setVisible(true);
        lblIVA.setVisible(true);
        lblTotal.setVisible(true);
        lblSubTotal.setVisible(true);
        lblNombreCliente.setVisible(true);
    }

    private void lblNoVisibles() {
        lblFechaIngreso.setVisible(false);
        lblFechaSalida.setVisible(false);
        lblIVA.setVisible(false);
        lblTotal.setVisible(false);
        lblSubTotal.setVisible(false);
        lblNombreCliente.setVisible(false);
    }

    public double calcuclarSubTotal() {
        String tipoHabitacion = ""; // Obtener el tipo de habitación seleccionado
        Habitacion habitacionSeleccionada = PaginaPrincipal.listaDeHabitaciones.
                get(indiceHabitacionSeleccionada);
        tipoHabitacion = habitacionSeleccionada.getTipoDeHabitacion();
        int diasTranscurridos = this.diasTranscurridos; // Obtener los días transcurridos

        double precioPorNoche = 0.0;
        switch (tipoHabitacion) {
            case "Matrimonial":
                precioPorNoche = 80.0;
                break;
            case "Triple":
                precioPorNoche = 115.0;
                break;
            case "Simple":
                precioPorNoche = 50.0;
                break;
            case "Cuadruple":
                precioPorNoche = 125.0;
                break;
            case "Connecting Rooms":
                precioPorNoche = 150.0;
                break;
            case "Suite":
                precioPorNoche = 180.0;
                break;
            default:
                break;
        }
        double Total = precioPorNoche * diasTranscurridos;
        return Total;
    }

    public double calcularPrecioTotal() {
        double iva = 0.12;
        double total = calcuclarSubTotal() + (calcuclarSubTotal() * iva);
        return total;

    }

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PnlFondo3;
    private javax.swing.ButtonGroup btgFormaDePago;
    private javax.swing.JButton btnCalcuclarReserva;
    private javax.swing.JButton btnFactura;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnNuevaReserva;
    private javax.swing.JButton btnSalir;
    private javax.swing.JScrollPane fondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane5;
    private com.toedter.calendar.JDateChooser jdcFechaIngreso;
    private com.toedter.calendar.JDateChooser jdcFechaSalida;
    private javax.swing.JLabel lblCliente4;
    private javax.swing.JLabel lblFechaIngreso;
    private javax.swing.JLabel lblFechaIngreso3;
    private javax.swing.JLabel lblFechaSalida;
    private javax.swing.JLabel lblFechaSalida3;
    private javax.swing.JLabel lblFormaPago3;
    private javax.swing.JLabel lblFormaPagoFactura3;
    private javax.swing.JLabel lblIVA;
    private javax.swing.JLabel lblIVA3;
    private javax.swing.JLabel lblNombreCliente;
    private javax.swing.JLabel lblNombreFactura3;
    private javax.swing.JLabel lblSubTotal;
    private javax.swing.JLabel lblTipoHabitacion3;
    private javax.swing.JLabel lblTipoHabitacionFactura3;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblTotal3;
    private javax.swing.JRadioButton rbtTarjeta;
    private javax.swing.JRadioButton rbtTransferencia;
    private javax.swing.JTable tblHabitacion21;
    private javax.swing.JTextArea txtDescripccion;
    // End of variables declaration//GEN-END:variables
}
